version: '3'
services:
  portainer:
    container_name: portainer
    image: portainer/portainer
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer_data:/data
    ports:
    - "9000:9000"
    hostname: portainer
    restart: always
